// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package db

import (
	"database/sql"
	"time"
)

type Article struct {
	ID        int64          `json:"id"`
	UserID    sql.NullInt64  `json:"user_id"`
	Title     sql.NullString `json:"title"`
	Content   sql.NullString `json:"content"`
	UpdatedAt time.Time      `json:"updated_at"`
	CreatedAt time.Time      `json:"created_at"`
}

type User struct {
	ID                int64     `json:"id"`
	Email             string    `json:"email"`
	HashedPassword    string    `json:"hashed_password"`
	Username          string    `json:"username"`
	IsEmailVerified   bool      `json:"is_email_verified"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
