// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Article struct {
	ID        int64          `json:"id"`
	UserID    sql.NullInt64  `json:"user_id"`
	Title     sql.NullString `json:"title"`
	Content   sql.NullString `json:"content"`
	UpdatedAt time.Time      `json:"updated_at"`
	CreatedAt time.Time      `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID    `json:"id"`
	UserID       int64        `json:"user_id"`
	RefreshToken string       `json:"refresh_token"`
	UserAgent    string       `json:"user_agent"`
	ClientIp     string       `json:"client_ip"`
	IsBlocked    bool         `json:"is_blocked"`
	ExpiresAt    time.Time    `json:"expires_at"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

type User struct {
	ID                int64     `json:"id"`
	Email             string    `json:"email"`
	HashedPassword    string    `json:"hashed_password"`
	Username          string    `json:"username"`
	IsEmailVerified   bool      `json:"is_email_verified"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
